### ISSUE TITLE
NullPointerException bei Klick auf properties bei Node 1

### ISSUE THREAD

**Issue by mrxder** [matpuz81/NetworkVisualizer#1]
java.lang.NullPointerException
    at networkvisualizer.NodeParameters.refreshList(NodeParameters.java:89)
    at networkvisualizer.NodeParameters.<init>(NodeParameters.java:54)
    at networkvisualizer.MenuListener.actionPerformed(MenuListener.java:51)

**Comment by mrxder** [comment]
OK
